// data-npcs.js — NPC compendium: tier recipes, NPC special abilities, 25 generic archetypes,
// iconic characters. T27 (recipes) + special-abilities list + T28 (25 generic stat blocks) +
// T29 (11 iconics) all EXTRACTED (2026-07-06). Known source gap: Rabban & Fenring numeric
// skills/drives are absent from the notebook (statsIncomplete:true) — an audit item, not a bug.
//
// Stat-block schema: { id, name, tier, tierInferred?, traits[], skills{5}, focuses[{skill,name}],
//   drives{5}, statements{<drive>:text}, talents[], assets[], note? }
// Skill/drive ids match the core schema (battle/communicate/discipline/move/understand;
// duty/faith/justice/power/truth). Tier is NOT printed on generic archetypes — it is inferred
// from the build (a skill of 8 exceeds the Notable fixed array's max of 7, so those read as
// Major; the rest as Notable). NPC talent names may include NPC-only special abilities that
// have no player-catalog entry — that is expected.

export const NPCS = {
  // ---------- T27 · NPC tier build recipes (§3.13) ----------
  tierRecipes: {
    general: {
      threatPerDetermination: 3,
      usesThreatNotMomentum: true,
      specialAbilitiesNote: 'NPCs may take NPC Special Abilities (see specialAbilities) in place of player talents.',
    },
    minor: {
      label: 'Minor',
      concept: 'Rank-and-file subordinates, servants, criminals, or soldiers.',
      traits: '1 trait describing the job/role (e.g. House Trooper, Servant, Spy).',
      drive: { type: 'single', range: [4, 8], typical: 5,
        note: 'One Quality/Drive rating added to the skill for any test; no individual drives or statements.' },
      skills: [6, 5, 5, 4, 4],
      focuses: { count: 1, note: '1 focus on the skill rated 6; a GM-granted 7 grants 2 focuses, an 8 grants 3.' },
      talents: { min: 0, max: 1, note: 'A talent or NPC special ability, often House training or a unique feature.' },
      defeat: 'A single successful attack defeats them.',
    },
    notable: {
      label: 'Notable',
      concept: 'Significant experts, specialists, or trusted lieutenants.',
      traits: '1 role trait; optional 2nd reputation trait (costs +1 Momentum/Threat to create in play).',
      drives: { high: [7, 6], rest: 5, statements: 1,
        statementsNote: '1 statement on a higher drive; a 2nd may be added at creation for +1 cost.' },
      skills: [7, 6, 5, 5, 4],
      focuses: { count: 3, note: '1 focus on the 6-skill and 2 on the 7-skill.' },
      talents: { min: 1, max: 2 },
      defeat: 'Extended task; requirement usually equals the NPC’s most appropriate skill.',
    },
    major: {
      label: 'Major',
      concept: 'Important, powerful individuals — equal or superior to the player characters.',
      traits: '2 traits (role + reputation); optional 3rd faction trait.',
      drives: { array: [8, 7, 6, 5, 4], statements: 'One per drive rated 6 or higher (3 total).' },
      skills: { base: 4, freePoints: 11, cap: 8,
        note: 'All five skills start at 4; assign 11 more points freely, none above 8.' },
      focuses: { min: 3, max: 5 },
      talents: { min: 2, max: 4, note: 'Talents or NPC special abilities.' },
      defeat: 'Extended task; requirement equals the foe’s most appropriate skill.',
    },
  },

  // ---------- NPC Special Abilities (taken in place of player talents) ----------
  specialAbilities: [
    { name: 'Proficiency', effect: 'Using a specific skill in a certain way, the first bonus d20 costs 0 to buy.' },
    { name: 'Threatening', effect: 'Using a specific skill/approach, when buying extra d20s with Threat, re-roll one d20.' },
    { name: 'Guidance', effect: 'Whenever you assist an ally in a certain way, re-roll your d20.' },
    { name: 'Substitution', effect: 'On a specific skill test you may use a specific other skill instead of the one normally required.' },
    { name: 'Familiarity', effect: 'On a specific skill test, reduce the Difficulty by 1 (minimum 0).' },
    { name: 'Additional Threat Option', effect: 'Gain a specific or unique benefit by spending 1 or more Threat.' },
  ],

  // ---------- T28 · Generic archetype stat blocks (25) ----------
  archetypes: [
    { id: 'arrakeenNative', name: 'Arrakeen Native', tier: 'notable', tierInferred: true,
      traits: ['Commoner'],
      skills: { battle: 3, communicate: 4, discipline: 6, move: 4, understand: 5 },
      focuses: [{ skill: 'discipline', name: 'Composure' }, { skill: 'discipline', name: 'Precision' }, { skill: 'understand', name: 'Advanced Technology' }],
      drives: { duty: 6, faith: 5, justice: 4, power: 4, truth: 4 },
      statements: { duty: 'Hard work and talent lead to advancement.' },
      talents: ['Cool Under Pressure (Discipline)'], assets: ['Tools of Trade', 'Workshop'] },

    { id: 'assassin', name: 'Assassin', tier: 'notable', tierInferred: true,
      traits: ['Assassin', 'Advisor to a Great House'],
      skills: { battle: 7, communicate: 4, discipline: 5, move: 6, understand: 4 },
      focuses: [{ skill: 'battle', name: 'Assassination' }, { skill: 'battle', name: 'Sneak Attacks' }, { skill: 'move', name: 'Stealth' }],
      drives: { duty: 6, faith: 4, justice: 4, power: 7, truth: 4 },
      statements: { power: 'Death determines who rules.' },
      talents: ['Master-at-Arms'], assets: ['Dartgun', 'Hunter-seeker', 'Poison'] },

    { id: 'beneGesseritAgent', name: 'Bene Gesserit Agent', tier: 'notable', tierInferred: true,
      traits: ['Bene Gesserit'],
      skills: { battle: 5, communicate: 4, discipline: 7, move: 6, understand: 5 },
      focuses: [{ skill: 'discipline', name: 'Composure' }, { skill: 'discipline', name: 'Espionage' }, { skill: 'move', name: 'Body Control' }],
      drives: { duty: 7, faith: 6, justice: 5, power: 5, truth: 5 },
      statements: { duty: 'I know my responsibilities.' },
      talents: ['Prana-Bindu Conditioning', 'Hyperawareness'], assets: ['Concealable Dagger', 'Dot Coder', 'Minimic Film (blank)'] },

    { id: 'beneGesseritReverendMother', name: 'Bene Gesserit Reverend Mother', tier: 'major', tierInferred: true,
      traits: ['Bene Gesserit', 'Reverend Mother'],
      skills: { battle: 5, communicate: 6, discipline: 7, move: 5, understand: 8 },
      focuses: [{ skill: 'discipline', name: 'Command' }, { skill: 'discipline', name: 'Composure' }, { skill: 'understand', name: 'Faction Lore (Bene Gesserit)' }],
      drives: { duty: 6, faith: 7, justice: 5, power: 5, truth: 6 },
      statements: { faith: 'The Sisterhood will prevail.' },
      talents: ['Hyperawareness', 'Other Memory', 'Prana-Bindu Conditioning', 'Voice'], assets: ['Dangerous Secret', 'Group of Bene Gesserit Acolytes', 'Robes of a Reverend Mother'] },

    { id: 'courtier', name: 'Courtier', tier: 'notable', tierInferred: true,
      traits: ['Courtier', 'Aristocrat'],
      skills: { battle: 4, communicate: 7, discipline: 6, move: 4, understand: 5 },
      focuses: [{ skill: 'communicate', name: 'Charm' }, { skill: 'communicate', name: 'Gossip' }, { skill: 'discipline', name: 'Espionage' }],
      drives: { duty: 5, faith: 6, justice: 5, power: 7, truth: 5 },
      statements: { faith: 'Arrakis needs the ruling class.' },
      talents: ['Mask of Power'], assets: ['Bodkin', 'Groundcar', 'Manor House'] },

    { id: 'criminal', name: 'Criminal', tier: 'notable', tierInferred: true,
      traits: ['Commoner', 'Lawless'],
      skills: { battle: 6, communicate: 4, discipline: 4, move: 6, understand: 4 },
      focuses: [{ skill: 'battle', name: 'Dirty Fighting' }, { skill: 'battle', name: 'Evasive Action' }, { skill: 'move', name: 'Stealth' }],
      drives: { duty: 4, faith: 4, justice: 4, power: 7, truth: 4 },
      statements: { power: 'I take what I need.' },
      talents: ['Make Haste'], assets: ['Krimskel Fiber Rope', 'Maula Pistol', 'Small Gang'] },

    { id: 'envoy', name: 'Envoy', tier: 'notable', tierInferred: true,
      traits: ['Diplomat', 'Traveler'],
      skills: { battle: 3, communicate: 7, discipline: 5, move: 5, understand: 6 },
      focuses: [{ skill: 'communicate', name: 'Charm' }, { skill: 'communicate', name: 'Diplomacy' }, { skill: 'understand', name: 'Etiquette' }],
      drives: { duty: 6, faith: 4, justice: 4, power: 4, truth: 7 },
      statements: { truth: 'The message is what matters.' },
      talents: ['Binding Promise'], assets: ['Cypher Key', 'Elegant Clothing', 'Local Agents of their House'] },

    { id: 'faceDancer', name: 'Face Dancer', tier: 'notable', tierInferred: true,
      traits: ['Imposter'],
      skills: { battle: 5, communicate: 7, discipline: 5, move: 6, understand: 5 },
      focuses: [{ skill: 'communicate', name: 'Acting' }, { skill: 'communicate', name: 'Disguise' }, { skill: 'move', name: 'Body Control' }],
      drives: { duty: 6, faith: 7, justice: 5, power: 5, truth: 4 },
      statements: { faith: 'The universe is as inconstant as I am.' },
      talents: ['Prana-Bindu', 'Facedance'], assets: [],
      note: 'Steals or copies the assets of whomever they mimic, often killing them to avoid exposure.' },

    { id: 'fremenElder', name: 'Fremen Elder', tier: 'major', tierInferred: true,
      traits: ['Fremen'],
      skills: { battle: 7, communicate: 4, discipline: 8, move: 6, understand: 5 },
      focuses: [{ skill: 'battle', name: 'Tactics' }, { skill: 'battle', name: 'Short Blades' }, { skill: 'discipline', name: 'Survival (Desert)' }, { skill: 'move', name: 'Worm Rider' }],
      drives: { duty: 5, faith: 7, justice: 6, power: 5, truth: 5 },
      statements: { faith: 'Arrakis will be transformed.' },
      talents: ['Binding Promise', 'Cautious (Discipline)', 'Resilience (Battle)'], assets: ['Crysknife', 'Maker Hooks', 'Small Band of Fremen Warriors', 'Stillsuit'] },

    { id: 'fremenWarrior', name: 'Fremen Warrior', tier: 'major', tierInferred: true,
      traits: ['Fremen'],
      skills: { battle: 8, communicate: 4, discipline: 7, move: 7, understand: 5 },
      focuses: [{ skill: 'battle', name: 'Dueling' }, { skill: 'battle', name: 'Short Blades' }, { skill: 'battle', name: 'Unarmed Combat' }, { skill: 'discipline', name: 'Survival (Desert)' }, { skill: 'discipline', name: 'Resolve' }, { skill: 'move', name: 'Worm Rider' }],
      drives: { duty: 7, faith: 8, justice: 6, power: 5, truth: 5 },
      statements: { duty: 'The sietch before all others.' },
      talents: ['Decisive Action', 'Nimble', 'Resilience (Battle)'], assets: ['Crysknife', 'Fremkit', 'Stillsuit'] },

    { id: 'guildAgent', name: 'Spacing Guild Agent', tier: 'notable', tierInferred: true,
      traits: ['Guild Agent', 'Diplomat'],
      skills: { battle: 4, communicate: 6, discipline: 7, move: 5, understand: 5 },
      focuses: [{ skill: 'communicate', name: 'Diplomacy' }, { skill: 'discipline', name: 'Composure' }, { skill: 'discipline', name: 'Self-Control' }],
      drives: { duty: 7, faith: 5, justice: 4, power: 5, truth: 6 },
      statements: { duty: 'The spice must flow.' },
      talents: ['Priority Boarding'], assets: ['Guild Contacts', 'Shield Belt', 'Supply Contracts'] },

    { id: 'healer', name: 'Healer', tier: 'notable', tierInferred: true,
      traits: ['Healer'],
      skills: { battle: 4, communicate: 5, discipline: 6, move: 6, understand: 7 },
      focuses: [{ skill: 'discipline', name: 'Composure' }, { skill: 'understand', name: 'Emergency Medicine' }, { skill: 'understand', name: 'Surgery' }],
      drives: { duty: 5, faith: 5, justice: 6, power: 5, truth: 7 },
      statements: { truth: 'A harsh truth is superior to a kind lie.' },
      talents: ['Intense Study'], assets: ['Glowglobe', 'Medical Records', 'Medkit'] },

    { id: 'houseSoldier', name: 'House Soldier', tier: 'notable', tierInferred: true,
      traits: ['Military'],
      skills: { battle: 6, communicate: 4, discipline: 5, move: 5, understand: 4 },
      focuses: [{ skill: 'battle', name: 'Lasgun' }, { skill: 'battle', name: 'Tactics' }, { skill: 'discipline', name: 'Composure' }],
      drives: { duty: 6, faith: 5, justice: 4, power: 4, truth: 4 },
      statements: { duty: 'I never desert my post.' },
      talents: ['Unquestionable Loyalty'], assets: ['Conscripts', 'Lasgun', 'Security Clearance', 'Shield Belt'] },

    { id: 'mentat', name: 'Mentat', tier: 'notable', tierInferred: true,
      traits: ['Mentat', 'Political Advisor'],
      skills: { battle: 5, communicate: 6, discipline: 4, move: 5, understand: 7 },
      focuses: [{ skill: 'communicate', name: 'Diplomacy' }, { skill: 'understand', name: 'Data Analysis' }, { skill: 'understand', name: 'Deductive Reasoning' }],
      drives: { duty: 6, faith: 5, justice: 5, power: 5, truth: 7 },
      statements: { truth: 'There is always a reason.' },
      talents: ['Mentat Discipline'], assets: ['Access to Employer Data', 'Informant Network', 'Sapho Juice'] },

    { id: 'merchant', name: 'Merchant', tier: 'notable', tierInferred: true,
      traits: ['Broker', 'Wealthy'],
      skills: { battle: 4, communicate: 6, discipline: 4, move: 4, understand: 5 },
      focuses: [{ skill: 'communicate', name: 'Bartering' }, { skill: 'communicate', name: 'Persuasion' }, { skill: 'understand', name: 'Data Analysis' }],
      drives: { duty: 5, faith: 5, justice: 6, power: 7, truth: 5 },
      statements: { power: 'There is power in solaris.' },
      talents: ['Driven'], assets: ['Information Network', 'Ornithopter', 'Warehouse'] },

    { id: 'nobleVeteran', name: 'Noble (Veteran)', tier: 'notable', tierInferred: true,
      traits: ['Noble'],
      skills: { battle: 5, communicate: 6, discipline: 6, move: 5, understand: 7 },
      focuses: [{ skill: 'communicate', name: 'Diplomacy' }, { skill: 'understand', name: 'House Politics' }, { skill: 'understand', name: 'Kanly' }],
      drives: { duty: 5, faith: 5, justice: 5, power: 7, truth: 6 },
      statements: { power: 'Possession is nine tenths of the law.' },
      talents: ['Putting Theory into Practice'], assets: ['Bodyguards', 'Kindjal Engraved with House Crest', 'Shield Belt'] },

    { id: 'nobleYoungHeir', name: 'Noble (Young Heir)', tier: 'notable', tierInferred: true,
      traits: ['Noble', 'House Minor'],
      skills: { battle: 5, communicate: 6, discipline: 7, move: 4, understand: 5 },
      focuses: [{ skill: 'communicate', name: 'Diplomacy' }, { skill: 'discipline', name: 'Command' }, { skill: 'discipline', name: 'Composure' }],
      drives: { duty: 7, faith: 5, justice: 6, power: 5, truth: 5 },
      statements: { duty: 'I am born to lead.' },
      talents: ['Bold (Communicate)'], assets: ['Influence', 'Kindjal', 'Ornithopter'] },

    { id: 'sardaukar', name: 'Sardaukar', tier: 'major', tierInferred: true,
      traits: ['Sardaukar', 'Soldier'],
      skills: { battle: 8, communicate: 5, discipline: 7, move: 7, understand: 4 },
      focuses: [{ skill: 'battle', name: 'Lasgun' }, { skill: 'battle', name: 'Long Blades' }, { skill: 'battle', name: 'Short Blades' }, { skill: 'battle', name: 'Tactics' }, { skill: 'discipline', name: 'Self-Control' }, { skill: 'move', name: 'Swift' }],
      drives: { duty: 8, faith: 5, justice: 5, power: 6, truth: 5 },
      statements: { duty: 'My knife is never sheathed.' },
      talents: ['Bolster', 'Decisive Action', 'Master-at-Arms'], assets: ['Lasgun', 'Shigawire Garrote', 'Shield', 'Kindjal', 'Flip-Dart'] },

    { id: 'scientist', name: 'Scientist', tier: 'notable', tierInferred: true,
      traits: ['Researcher'],
      skills: { battle: 3, communicate: 4, discipline: 6, move: 4, understand: 7 },
      focuses: [{ skill: 'discipline', name: 'Observe' }, { skill: 'understand', name: 'Deductive Reasoning' }, { skill: 'understand', name: 'Physics' }],
      drives: { duty: 5, faith: 5, justice: 5, power: 4, truth: 7 },
      statements: { truth: 'Science will solve the problem.' },
      talents: ['Intense Study'], assets: ['Shigawire Reels', 'Laboratory', 'Data About Arrakis'] },

    { id: 'servant', name: 'Servant', tier: 'notable', tierInferred: true,
      traits: ['Servant'],
      skills: { battle: 3, communicate: 5, discipline: 6, move: 6, understand: 4 },
      focuses: [{ skill: 'communicate', name: 'Listening' }, { skill: 'move', name: 'Unobtrusive' }, { skill: 'understand', name: 'Etiquette' }],
      drives: { duty: 4, faith: 4, justice: 4, power: 5, truth: 6 },
      statements: { truth: 'What one wishes were true is seldom so.' },
      talents: ['Nimble'], assets: ['Illicit Recordings', 'Old Friendship', 'Trusted Access'] },

    { id: 'smuggler', name: 'Smuggler', tier: 'notable', tierInferred: true,
      traits: ['Smuggler'],
      skills: { battle: 5, communicate: 4, discipline: 3, move: 6, understand: 5 },
      focuses: [{ skill: 'battle', name: 'Dirty Fighting' }, { skill: 'move', name: 'Drive' }, { skill: 'move', name: 'Stealth' }],
      drives: { duty: 5, faith: 5, justice: 7, power: 6, truth: 5 },
      statements: { justice: 'They will not control us.' },
      talents: ['Constantly Watching'], assets: ['Hidden Base', 'Maula Pistol', 'Ornithopter'] },

    { id: 'spyInfiltrator', name: 'Spy (Infiltrator)', tier: 'notable', tierInferred: true,
      traits: ['Imposter', 'Spy'],
      skills: { battle: 5, communicate: 6, discipline: 5, move: 5, understand: 7 },
      focuses: [{ skill: 'communicate', name: 'Deceit' }, { skill: 'understand', name: 'Danger Sense' }, { skill: 'understand', name: 'Traps' }],
      drives: { duty: 6, faith: 5, justice: 5, power: 5, truth: 7 },
      statements: { truth: 'The truth is what you make it.' },
      talents: ['Ransack'], assets: ['Cibus Hood', 'Lockpicks', 'Memocorder'] },

    { id: 'technician', name: 'Technician', tier: 'notable', tierInferred: true,
      traits: ['Technician'],
      skills: { battle: 3, communicate: 4, discipline: 6, move: 4, understand: 6 },
      focuses: [{ skill: 'discipline', name: 'Precision' }, { skill: 'understand', name: 'Advanced Technology' }, { skill: 'understand', name: 'Deductive Reasoning' }],
      drives: { duty: 5, faith: 6, justice: 4, power: 4, truth: 5 },
      statements: { faith: 'My skills will keep us running.' },
      talents: ['Rigorous Control'], assets: ['Technical Access', 'Tools', 'Vision Enhancement Goggles'] },

    { id: 'tleilaxuMaster', name: 'Tleilaxu Master', tier: 'notable', tierInferred: true,
      traits: ['Tleilaxu', 'Biologist'],
      skills: { battle: 3, communicate: 6, discipline: 6, move: 5, understand: 7 },
      focuses: [{ skill: 'communicate', name: 'Neurolinguistics' }, { skill: 'understand', name: 'Genetics' }, { skill: 'understand', name: 'Faction Lore (Tleilaxu)' }],
      drives: { duty: 5, faith: 6, justice: 3, power: 5, truth: 7 },
      statements: { truth: 'Science holds the answers.' },
      talents: ['Masterful Innuendo'], assets: ['Face Dancer', 'Illicit Recordings', 'Ixian Damper'] },

    { id: 'waterSeller', name: 'Water Seller', tier: 'notable', tierInferred: true,
      traits: ['Water Seller', 'Merchant'],
      skills: { battle: 2, communicate: 6, discipline: 4, move: 4, understand: 5 },
      focuses: [{ skill: 'communicate', name: 'Bartering' }, { skill: 'communicate', name: 'Gossip' }],
      drives: { duty: 4, faith: 4, justice: 5, power: 6, truth: 4 },
      statements: { power: 'Everyone wants water.' },
      talents: ['Subtle Words'], assets: ['Small Group of Thugs', 'Water', 'Wealth'] },
  ],

  // ---------- T29 · Iconic character stat blocks (12) ----------
  // Tier is not printed for iconics; all read as Major. Iconic stat blocks print NO asset
  // lines (owner-confirmed against the book, 2026-07-06) — assets stay [] by design.
  // Rabban, Fenring, Paul, and Feyd-Rautha were all completed from the owner's transcription
  // of the printed book (2026-07-06); the notebook excerpts had cut off or (for Feyd) served
  // Rabban's adjacent numbers by mistake. All 12 iconic blocks are now complete and verified.
  iconicsNote: 'All 12 iconic stat blocks complete. Iconic blocks print no asset lines (assets: [] by design). No Paul block existed in the notebook; Rabban/Fenring/Paul/Feyd came from the owner’s printed-book transcription.',
  iconics: [
    { id: 'letoAtreides', name: 'Duke Leto Atreides', tier: 'major', tierInferred: true,
      traits: ['Noble', 'Fair and Honorable'],
      skills: { battle: 6, communicate: 7, discipline: 7, move: 5, understand: 6 },
      focuses: [{ skill: 'communicate', name: 'Charm' }, { skill: 'communicate', name: 'Diplomacy' }, { skill: 'communicate', name: 'Empathy' }, { skill: 'discipline', name: 'Composure' }, { skill: 'understand', name: 'House Politics' }, { skill: 'understand', name: 'Imperial Politics' }],
      drives: { duty: 8, faith: 5, justice: 7, power: 4, truth: 6 },
      statements: { duty: "My House, my family, and my people: all are one.", justice: "Law must rule the people, but the heart must rule the law.", truth: "Part of courage comes from extending our knowledge." },
      talents: ['Bolster', 'Direct', 'Stirring Rhetoric'], assets: [] },

    { id: 'ladyJessica', name: 'Lady Jessica', tier: 'major', tierInferred: true,
      traits: ['Consort', 'Bene Gesserit', 'Dedicated', 'Devoted'],
      skills: { battle: 6, communicate: 6, discipline: 7, move: 7, understand: 6 },
      focuses: [{ skill: 'battle', name: 'Short Blades' }, { skill: 'communicate', name: 'Persuasion' }, { skill: 'discipline', name: 'Self-Control' }, { skill: 'move', name: 'Body Control' }, { skill: 'understand', name: 'Etiquette' }, { skill: 'understand', name: 'Faction Lore (Bene Gesserit)' }],
      drives: { duty: 7, faith: 8, justice: 6, power: 4, truth: 5 },
      statements: { duty: "The Sisterhood is my family.", faith: "Leto and my son are everything.", justice: "I will pay for my own mistakes." },
      talents: ['Hyperawareness', 'Passive Scrutiny', 'Prana-Bindu Conditioning', 'Voice'], assets: [] },

    { id: 'paulAtreides', name: 'Paul Atreides', tier: 'major', tierInferred: true,
      traits: ['Noble Scion', 'Wise Beyond His Years', 'Destined for Greatness'],
      skills: { battle: 6, communicate: 5, discipline: 6, move: 5, understand: 6 },
      focuses: [{ skill: 'battle', name: 'Shield Fighting' }, { skill: 'battle', name: 'Short Blades' }, { skill: 'communicate', name: 'Charm' }, { skill: 'discipline', name: 'Precision' }, { skill: 'discipline', name: 'Self-Control' }, { skill: 'move', name: 'Body Control' }, { skill: 'understand', name: 'Imperial Politics' }],
      drives: { duty: 6, faith: 7, justice: 4, power: 5, truth: 8 },
      statements: { duty: 'People are the true strength of a Great House.', faith: "I must learn quickly to be worthy of my father's legacy.", truth: 'There are problems in this universe for which there are no answers.' },
      talents: ['Cool Under Pressure (Battle)', 'Direct', 'Prana-Bindu Conditioning', 'The Slow Blade', 'Voice'], assets: [],
      note: 'Printed header: “Kwisatz Haderach in Waiting”. From the owner’s book transcription (2026-07-06); the notebook excerpts lacked this block.' },

    { id: 'gurneyHalleck', name: 'Gurney Halleck', tier: 'major', tierInferred: true,
      traits: ['Warrior', 'Jongleur'],
      skills: { battle: 8, communicate: 6, discipline: 7, move: 6, understand: 5 },
      focuses: [{ skill: 'battle', name: 'Short Blades' }, { skill: 'battle', name: 'Tactics' }, { skill: 'communicate', name: 'Music (Baliset)' }, { skill: 'discipline', name: 'Resolve' }],
      drives: { duty: 8, faith: 4, justice: 7, power: 5, truth: 6 },
      statements: { duty: "The Atreides have given me everything, I will do the same in return.", justice: "There's no justice but what we make ourselves.", truth: "Truth's a complex thing, but we know it when we see it." },
      talents: ['Bolster', 'The Reason I Fight (Duty)', 'The Slow Blade', 'Unquestionable Loyalty (House Atreides)'], assets: [] },

    { id: 'thufirHawat', name: 'Thufir Hawat', tier: 'major', tierInferred: true,
      traits: ['Mentat', 'Insightful and Resourceful', 'Spymaster'],
      skills: { battle: 6, communicate: 5, discipline: 7, move: 5, understand: 8 },
      focuses: [{ skill: 'battle', name: 'Assassination' }, { skill: 'battle', name: 'Strategy' }, { skill: 'discipline', name: 'Observe' }, { skill: 'understand', name: 'Data Analysis' }, { skill: 'understand', name: 'Deductive Reasoning' }, { skill: 'understand', name: 'Imperial Politics' }, { skill: 'understand', name: 'Kanly' }],
      drives: { duty: 8, faith: 4, justice: 6, power: 5, truth: 7 },
      statements: { duty: "The protection of the Atreides is my reason to live.", justice: "Right and wrong must be measured against my responsibilities.", truth: "The primacy of my agenda is ruled only by fact." },
      talents: ['Advisor (Understand)', 'Cautious (Understand)', 'Mentat Discipline', 'Mind Palace'], assets: [] },

    { id: 'duncanIdaho', name: 'Duncan Idaho', tier: 'major', tierInferred: true,
      traits: ['Charismatic Survivor', 'Ginaz Swordmaster'],
      skills: { battle: 8, communicate: 6, discipline: 8, move: 6, understand: 5 },
      focuses: [{ skill: 'battle', name: 'Long Blades' }, { skill: 'communicate', name: 'Charm' }, { skill: 'discipline', name: 'Resolve' }, { skill: 'move', name: 'Distance Running' }],
      drives: { duty: 8, faith: 7, justice: 6, power: 4, truth: 5 },
      statements: { duty: "I will give my all for those I have sworn to protect.", faith: "The universe is vast, a man must find his own way.", justice: "My own word and oath are all I need to measure the deeds of others." },
      talents: ['Bold (Battle)', 'Driven', 'Make Haste', 'Master-at-Arms'], assets: [] },

    { id: 'wellingtonYueh', name: 'Dr. Wellington Yueh', tier: 'major', tierInferred: true,
      traits: ['Suk Doctor', 'Despises the Harkonnens'],
      skills: { battle: 4, communicate: 7, discipline: 5, move: 4, understand: 8 },
      focuses: [{ skill: 'communicate', name: 'Deceit' }, { skill: 'communicate', name: 'Teaching' }, { skill: 'understand', name: 'Genetics' }, { skill: 'understand', name: 'Surgery' }],
      drives: { duty: 4, faith: 7, justice: 8, power: 5, truth: 6 },
      statements: { faith: "Who can believe in a greater power when evil is unavoidable?", justice: "My course of action is terrible, yet I must find a way to do right.", truth: "I do not know what is true anymore, but I will act nonetheless." },
      talents: ['Advisor (Understand)', 'Imperial Conditioning', 'Intense Study'], assets: [] },

    { id: 'feydRautha', name: 'Feyd-Rautha Harkonnen', tier: 'major', tierInferred: true,
      traits: ['Duelist', 'Arrogant and Ruthless'],
      skills: { battle: 7, communicate: 6, discipline: 5, move: 7, understand: 6 },
      focuses: [{ skill: 'battle', name: 'Short Blades' }, { skill: 'communicate', name: 'Intimidation' }, { skill: 'communicate', name: 'Listening' }, { skill: 'move', name: 'Swift' }],
      drives: { duty: 6, faith: 7, justice: 4, power: 8, truth: 5 },
      statements: { duty: 'I serve the House because it will one day be mine.', faith: 'I am the best at everything I do.', power: 'I deserve to have everything I want.' },
      talents: ['Bold (Battle)', 'Decisive Action', 'Rapid Maneuver', 'The Reason I Fight (Power)', 'The Slow Blade'], assets: [],
      note: 'Printed header: “Elegant Knife Fighter”. From the owner’s book transcription (2026-07-06), which corrected the notebook’s conflation with Rabban (skills/focuses/statements differ; drives coincidentally matched). Lore notes he favours poisoned blades.' },

    { id: 'glossuRabban', name: 'Glossu Rabban (the Beast)', tier: 'major', tierInferred: true,
      traits: ['Thuggish Tyrant', 'Brutal and Vicious'],
      skills: { battle: 7, communicate: 5, discipline: 5, move: 6, understand: 4 },
      focuses: [{ skill: 'battle', name: 'Lasgun' }, { skill: 'communicate', name: 'Intimidation' }, { skill: 'move', name: 'Stealth' }],
      drives: { duty: 6, faith: 7, justice: 4, power: 8, truth: 5 },
      statements: { duty: 'Fear keeps subordinates in line.', faith: "I don't need to understand a plan to know it will benefit me.", power: "I'm stronger so I'm better." },
      talents: ['Bold (Battle)', 'Make Haste', 'Master-at-Arms'], assets: [],
      note: 'Printed header: “Brutal Warrior”. From the owner’s book transcription (2026-07-06).' },

    { id: 'hasimirFenring', name: 'Count Hasimir Fenring', tier: 'major', tierInferred: true,
      traits: ['Noble Courtier', 'Assassin', 'Psychopath'],
      skills: { battle: 7, communicate: 6, discipline: 6, move: 8, understand: 6 },
      focuses: [{ skill: 'battle', name: 'Assassination' }, { skill: 'discipline', name: 'Command' }, { skill: 'move', name: 'Stealth' }, { skill: 'understand', name: 'Poison' }],
      drives: { duty: 7, faith: 4, justice: 6, power: 8, truth: 5 },
      statements: { duty: 'What is expected of me is the least of my obligations.', justice: 'Law is the concern of lawyers and victims.', power: 'I do as I please.' },
      talents: ['Advisor (Battle)', 'Hidden Motives', 'Passive Scrutiny', 'Subtle Step', 'Subtle Words', 'To Fight Someone Is to Know Them (Understand)'], assets: [],
      note: 'Printed header: “Courtier Assassin”. From the owner’s book transcription (2026-07-06).' },

    { id: 'stilgar', name: 'Stilgar', tier: 'major', tierInferred: true,
      traits: ['Fremen Leader', 'Fierce and Dedicated'],
      skills: { battle: 7, communicate: 5, discipline: 7, move: 6, understand: 5 },
      focuses: [{ skill: 'battle', name: 'Short Blades' }, { skill: 'communicate', name: 'Intimidation' }, { skill: 'discipline', name: 'Command' }, { skill: 'move', name: 'Worm Rider' }],
      drives: { duty: 7, faith: 8, justice: 6, power: 4, truth: 5 },
      statements: { duty: "The tribe's life is my own.", faith: "Shai-Hulud shows us the way.", justice: "Harsh laws are needed in a harsh world, but we must know mercy in all its forms." },
      talents: ['Cautious (Battle)', 'Cool Under Pressure (Move)', 'Deliberate Motion', 'Rigorous Control', 'To Fight Someone Is to Know Them (Battle)'], assets: [] },

    { id: 'lietKynes', name: 'Liet Kynes', tier: 'major', tierInferred: true,
      traits: ['Fremen', 'Planetologist'],
      skills: { battle: 5, communicate: 6, discipline: 7, move: 4, understand: 7 },
      focuses: [{ skill: 'discipline', name: 'Survival (Desert)' }, { skill: 'understand', name: 'Botany' }, { skill: 'understand', name: 'Ecology' }],
      drives: { duty: 6, faith: 8, justice: 5, power: 4, truth: 7 },
      statements: { duty: "I owe the Emperor my allegiance but the Fremen my life.", faith: "The desert will provide the Faithful with what they need.", truth: "Fact cannot be obscured, only confused." },
      talents: ['Cautious (Understand)', 'Collaboration (Understand)', 'Unquestionable Loyalty'], assets: [] },
  ],
};
