// data-oracle.js — Homebrew GM/solo "oracle" idea-generator tables.
//
// NOT rulebook content (§2/§10.8): these are house-made brainstorming word lists for solo play or
// GM prep, not official Dune: Adventures in the Imperium rules. Labeled as such in the UI. Roll a
// d100 on each of the four tables → one word each → a 4-word seed to spark a scene/beat.
//
// Index 0 = roll 1 … index 99 = roll 100.

export const ORACLE = {
  note: 'Homebrew idea generator — not official rules. Roll for a spark, then add it to your journal.',
  tables: [
    {
      id: 'action', label: 'Action',
      words: [
        'Abandon', 'Adapt', 'Ally', 'Ambush', 'Annihilate', 'Assassinate', 'Avenge', 'Awaken', 'Banish', 'Betray',
        'Bless', 'Breed', 'Bribe', 'Capture', 'Challenge', 'Change', 'Claim', 'Command', 'Compel', 'Conceal',
        'Condition', 'Conquer', 'Conspire', 'Continue', 'Convert', 'Crown', 'Curse', 'Deceive', 'Decode', 'Defy',
        'Detonate', 'Distill', 'Dominate', 'Dream', 'Encircle', 'Endure', 'Enslave', 'Escape', 'Escort', 'Excavate',
        'Exile', 'Explore', 'Expose', 'Feint', 'Flee', 'Foresee', 'Fortify', 'Guard', 'Harvest', 'Hunt',
        'Infiltrate', 'Interrogate', 'Irrigate', 'Kneel', 'Liberate', 'Manipulate', 'Marry', 'Meditate', 'Migrate', 'Mourn',
        'Mutate', 'Navigate', 'Negotiate', 'Observe', 'Overrun', 'Parry', 'Pledge', 'Plot', 'Poison', 'Preach',
        'Preserve', 'Prophesy', 'Protect', 'Provoke', 'Punish', 'Purge', 'Raid', 'Ration', 'Reclaim', 'Recruit',
        'Rescue', 'Reveal', 'Revolt', 'Ride', 'Sabotage', 'Sacrifice', 'Salvage', 'Scheme', 'Slay', 'Smuggle',
        'Spy', 'Stalk', 'Start', 'Stop', 'Submit', 'Summon', 'Survive', 'Terraform', 'Track', 'Train',
      ],
    },
    {
      id: 'descriptor', label: 'Descriptor',
      words: [
        'Addictive', 'Alien', 'Amber', 'Ancient', 'Apocalyptic', 'Arid', 'Aristocratic', 'Armored', 'Artificial', 'Austere',
        'Azure', 'Barren', 'Blinding', 'Buried', 'Calculated', 'Ceremonial', 'Colossal', 'Contested', 'Corrupt', 'Coveted',
        'Cruel', 'Cunning', 'Damned', 'Decadent', 'Dehydrated', 'Desolate', 'Destined', 'Devious', 'Devout', 'Disciplined',
        'Distant', 'Divine', 'Doomed', 'Dreadful', 'Duplicitous', 'Dynastic', 'Efficient', 'Embattled', 'Endless', 'Eternal',
        'Euphoric', 'Fanatical', 'Fated', 'Feral', 'Feudal', 'Fierce', 'Forbidden', 'Foreboding', 'Galactic', 'Genetic',
        'Glowing', 'Golden', 'Hallowed', 'Hardened', 'Harsh', 'Hereditary', 'Heretical', 'Hoarded', 'Holy', 'Hooded',
        'Hostile', 'Immortal', 'Imperial', 'Inevitable', 'Intoxicating', 'Isolated', 'Lavish', 'Lethal', 'Logical', 'Masked',
        'Merciless', 'Monstrous', 'Mundane', 'Mysterious', 'Noble', 'Nomadic', 'Offworld', 'Ominous', 'Opulent', 'Oracular',
        'Paranoid', 'Parched', 'Precious', 'Precise', 'Prescient', 'Primal', 'Rhythmic', 'Royal', 'Ruthless', 'Sacred',
        'Savage', 'Scarce', 'Scarred', 'Scorched', 'Searing', 'Secretive', 'Silent', 'Strange', 'Subterranean', 'Twisted',
      ],
    },
    {
      id: 'event', label: 'Event',
      words: [
        'Alliance', 'Anointing', 'Ascension', 'Assassination', 'Auction', 'Audience', 'Betrothal', 'Birth', 'Blockade', 'Bombardment',
        'Boom', 'Bounty', 'Ceasefire', 'Census', 'Collapse', 'Conclave', 'Conscription', 'Coronation', 'Council', 'Coup',
        'Crash', 'Crossing', 'Crusade', 'Decrease', 'Defection', 'Disappearance', 'Discovery', 'Drought', 'Duel', 'Eclipse',
        'Embargo', 'Emergence', 'Emissary', 'Epidemic', 'Eruption', 'Execution', 'Exodus', 'Expulsion', 'Extra', 'Famine',
        'Feast', 'Festival', 'Feud', 'Funeral', 'Gathering', 'Heist', 'Increase', 'Infestation', 'Inheritance', 'Inquisition',
        'Insurrection', 'Invasion', 'Judgment', 'Kidnapping', 'Landing', 'Levy', 'Manhunt', 'Massacre', 'Miracle', 'Mutiny',
        'Omen', 'Ordeal', 'Outbreak', 'Parley', 'Pilgrimage', 'Plague', 'Portent', 'Proclamation', 'Quake', 'Ransom',
        'Rebellion', 'Rebirth', 'Reckoning', 'Reunion', 'Riot', 'Ritual', 'Rumor', 'Sandstorm', 'Scandal', 'Shortage',
        'Siege', 'Skirmish', 'Stampede', 'Standoff', 'Succession', 'Summit', 'Surrender', 'Swarm', 'Tempest', 'Theft',
        'Treason', 'Trial', 'Tribunal', 'Truce', 'Uprising', 'Verdict', 'Vigil', 'Wedding', 'Windfall', 'Withdrawal',
      ],
    },
    {
      id: 'lore', label: 'Lore',
      words: [
        'Abomination', 'Amtal', 'Arrakeen', 'Arrakis', 'Atomics', 'Atreides', 'Axlotl', 'Baliset', 'Bashar', 'Bindu',
        'Bled', 'Butlerian', 'Caladan', 'Carryall', 'Carthag', 'Chakobsa', 'Chapterhouse', 'Chaumurky', 'CHOAM', 'Coriolis',
        'Corrino', 'Crysknife', 'Deathstill', 'Distrans', 'Drumsand', 'Ecaz', 'Elacca', 'Erg', 'Facedancer', 'Faufreluches',
        'Fedaykin', 'Filmbook', 'Fremkit', 'Galach', 'Gammu', 'Ghola', 'Giedi', 'Ginaz', 'Glowglobe', 'Grumman',
        'Harkonnen', 'Harvester', 'Heighliner', 'Holtzman', 'Hunter-Seeker', 'Imperium', 'Ix', 'Kaitain', 'Kanly', 'Karama',
        'Kwisatz', 'Landsraad', 'Lasgun', 'Litany', 'Mahdi', 'Maker', 'Maula', 'Missionaria', 'Naib', 'No-ship',
        'Ornithopter', 'Padishah', 'Paracompass', 'Prana', 'Qanat', 'Qizarate', 'Rakis', 'Razzia', 'Richese', 'Salusa',
        'Sandrider', 'Sandtrout', 'Sandwalk', 'Sapho', 'Sardaukar', 'Sayyadina', 'Scattering', 'Semuta', 'Shadout', 'Shai-Hulud',
        'Shaitan', 'Shigawire', 'Snooper', 'Spiceblow', 'Stoneburner', 'Suk', 'Suspensor', 'Swordmaster', 'Tabr', 'Tanzerouft',
        'Tau', 'Thumper', 'Tleilax', 'Tleilaxu', 'Truthsayer', 'Tupile', 'Verite', 'Wallach', 'Weirding', 'Windtrap',
      ],
    },
  ],
  // Yes/No oracle (homebrew, Mythic-style): pick a likelihood, roll d100, answer Yes if roll ≤ its
  // chance; doubles (11,22,…,99,00) add a complication ("but…"). Numbers live here, not in the module.
  yesNo: {
    note: 'Ask a yes/no question, pick how likely, and roll. Doubles add a complication.',
    doublesNote: 'Doubles (11, 22, … 00) = the answer comes with a complication.',
    tiers: [
      { id: 'unlikely', label: 'Unlikely', yes: 35 },
      { id: 'even', label: 'Even', yes: 50 },
      { id: 'likely', label: 'Likely', yes: 65 },
    ],
  },

  // Chaos Factor (homebrew solo-play engine): how unstable the story is right now.
  // Scene check = d10; roll ≤ chaos means the scene doesn't start as framed (odd = interrupted by
  // an event, even = altered). Chaos also shifts the yes/no odds linearly around its pivot.
  chaos: {
    min: 1, max: 9, start: 5, pivot: 5,
    oddsShiftPerStep: 5, minChance: 5, maxChance: 95,
    note: 'Chaos rises when events run away from you and falls when you stay in control. It steers the scene check and the oracle odds.',
    sceneNote: 'Roll d10 against Chaos: higher than Chaos = the scene runs as you framed it. Equal or lower = odd is interrupted, even is altered.',
    endNote: 'In control at the end of the scene → Chaos −1. Not in control → Chaos +1.',
    outcomes: {
      expected: { label: 'As expected', desc: 'Play the scene the way you framed it.' },
      altered: { label: 'Altered', desc: 'Something about the framing is wrong — change one detail before you play it.' },
      interrupted: { label: 'Interrupted', desc: 'Set the framed scene aside; the event below happens instead.' },
    },
  },

  // In-app help copy for the solo Journal (steps + a worked example per section). Shared by the
  // Journal's collapsed "How to use" accordions and the tutorial's solo lesson, so both stay in step.
  help: {
    overview: {
      title: 'How to play solo',
      intro: 'With no GM, you frame each scene yourself and let the dice answer the questions you can’t. One scene at a time, the loop is:',
      steps: [
        'Frame the scene you expect — where you are, who is there, what you want.',
        'Run the scene check. Chaos decides whether the story cooperates: the scene plays as framed, gets altered, or is interrupted by an event.',
        'Play it out in the notes. When you hit a question only the world can answer, consult the oracle.',
        'End the scene. Say whether you were in control, which moves Chaos, and the scene is logged as an entry.',
        'Keep threads and NPCs current — random events draw on those lists, so the story feeds itself.',
      ],
      example: 'Chaos 5. You frame "I search the Duke\'s study for the poisoner\'s trail." The scene check rolls d10 = 3 — that\'s ≤ 5 and odd, so the scene is interrupted: the event says "A known face acts (Stilgar) · Conceal / Ominous". Stilgar is already there, hiding something. You play that instead, ask the oracle "Does he admit it?" (Unlikely) and get "No, but… (complication)". At the end you were not in control, so Chaos rises to 6.',
      closing: 'Your character sheet, dice roller and rules library all still work — the Journal only replaces the GM.',
    },
    sections: {
      scene: {
        steps: [
          'Check the Chaos Factor. It starts at 5 and rises when things run away from you; use ± only to correct it by hand.',
          'Write the scene you expect in "Frame the scene".',
          'Press Scene check. Higher than Chaos = play it as framed. Equal or lower = altered (change one detail) or interrupted (an event happens instead).',
          'Press Add to scene to paste the result — and any event — into your notes.',
          'Play the scene out in "Play it out", consulting the oracle as questions come up.',
          'Press End scene, answer whether you were in control, and the scene is logged and the pad cleared.',
        ],
        example: 'Chaos 5, d10 rolls 4 → 4 is ≤ 5 and even, so the scene is Altered: you framed a quiet study, but change one detail — the door is already open.',
      },
      oracle: {
        steps: [
          'Phrase your question so yes or no is a real answer ("Is the guard still at his post?").',
          'Pick how likely a yes feels. The percentage shown already includes the current Chaos Factor.',
          'Press Consult. Doubles (11, 22, … 00) add a complication to whichever way it lands.',
          'Press Add to scene to drop the answer into the scene notes, or Log as entry to record it on its own.',
          'Take the answer as true and keep playing — don’t re-roll a question you dislike.',
        ],
        example: '"Is the guard still at his post?" at Likely with Chaos 7 reads 75%. You roll 33 — a yes, and doubles, so: "Yes, but… (complication)". He is there, but he has already seen you.',
      },
      entries: {
        steps: [
          'Ending a scene writes an entry for you — that is the usual way this list grows.',
          'Use "+ New entry" for anything outside a scene: downtime, a letter, a realisation.',
          'Give an entry a title when you want to find it again later.',
          'Link an entry to an open thread to keep that storyline together.',
          'Delete an entry with × delete if it was a mistake.',
        ],
        example: 'After the study scene you add a separate entry titled "What I now believe", linked to the thread "Who poisoned the Duke?".',
      },
      threads: {
        steps: [
          'Add a thread for every open question or goal you want the story to chase.',
          'Phrase it as a question ("Who poisoned the Duke?") or a goal ("Reach Sietch Tabr").',
          'Use note to record what you have learned so far.',
          'Press resolve when the story answers it; reopen if it comes back.',
          'Keep at least a couple open — random events pull from this list.',
        ],
        example: 'The event "Thread advances — Who poisoned the Duke?" tells you this scene brings that answer closer, so you play a scene where the trail warms.',
      },
      contacts: {
        steps: [
          'Add an NPC or a place the moment it matters in play.',
          'Use note for what you know: allegiance, what they want, what they owe you.',
          'Keep the list trimmed to names still in the story.',
          'Random events draw from this list, so anyone here can walk back on stage.',
        ],
        example: 'You record "Stilgar — NPC, sietch naib, does not trust offworlders". Later an event rolls "A known face acts (Stilgar)" and he arrives with a demand.',
      },
    },
  },

  // Random-event focus (d100, homebrew Dune-flavored — not another product's table).
  // `pull` tells the app what to draw from your journal: an open thread, a known NPC/place, or nothing.
  eventFocus: [
    { max: 7,   label: 'Distant upheaval',     pull: null,     desc: 'Something far off shifts — a world, a House, a fleet.' },
    { max: 28,  label: 'A known face acts',    pull: 'contact', desc: 'Someone already in your journal makes a move.' },
    { max: 35,  label: 'A stranger arrives',   pull: null,     desc: 'Introduce someone new to the story.' },
    { max: 45,  label: 'Thread advances',      pull: 'thread', desc: 'An open question moves closer to an answer.' },
    { max: 52,  label: 'Thread frustrated',    pull: 'thread', desc: 'An open question is pushed further out of reach.' },
    { max: 55,  label: 'Thread resolves',      pull: 'thread', desc: 'An open question is answered now — close it.' },
    { max: 67,  label: 'Turned against you',   pull: null,     desc: 'The situation moves against you.' },
    { max: 75,  label: 'Turned in your favor', pull: null,     desc: 'The situation breaks your way.' },
    { max: 83,  label: 'Ambiguous omen',       pull: null,     desc: 'A sign whose meaning is not yet clear.' },
    { max: 92,  label: 'Setback for another',  pull: 'contact', desc: 'Someone else in your journal suffers for it.' },
    { max: 100, label: 'Fortune for another',  pull: 'contact', desc: 'Someone else in your journal gains by it.' },
  ],
  // Short glosses (<14 words) for the Lore table — tap a lore result for a reminder.
  // Homebrew paraphrase of general Herbert canon, not rulebook prose (§10.8/§12).
  loreDefs: {
    Abomination: 'A pre-born child possessed by adult ancestral memories.',
    Amtal: 'Testing a thing to destruction to learn its limits.',
    Arrakeen: 'First settlement and capital city of Arrakis.',
    Arrakis: 'The desert planet Dune, sole source of spice melange.',
    Atomics: 'Family nuclear weapons held by each Great House.',
    Atreides: 'Noble House of Duke Leto; the protagonists.',
    Axlotl: 'Tleilaxu tanks that grow gholas and biological products.',
    Baliset: 'Nine-string instrument; Gurney Halleck plays one.',
    Bashar: 'A Sardaukar colonel-level military officer.',
    Bindu: 'Nervous-system control in Bene Gesserit prana-bindu training.',
    Bled: 'The flat, open desert of Arrakis.',
    Butlerian: 'The Jihad that outlawed thinking machines.',
    Caladan: 'Lush ocean world, ancestral Atreides homeworld.',
    Carryall: 'Aircraft that lifts and moves spice harvesters.',
    Carthag: 'Second major Arrakeen city, built by the Harkonnens.',
    Chakobsa: 'The ancient hunting language of the Fremen.',
    Chapterhouse: 'Later hidden homeworld of the Bene Gesserit.',
    Chaumurky: 'Poison administered in a drink.',
    CHOAM: 'Empire-spanning company controlling all interstellar trade.',
    Coriolis: 'A vast Arrakis sandstorm driven by planetary winds.',
    Corrino: 'Imperial House of Padishah Emperor Shaddam IV.',
    Crysknife: "Sacred Fremen blade made from a sandworm's tooth.",
    Deathstill: "Device reclaiming a corpse's water for the tribe.",
    Distrans: "Message encoded within a creature's nervous system.",
    Drumsand: 'Sand that booms underfoot, attracting sandworms.',
    Ecaz: 'House and world famed for fogwood and art.',
    Elacca: 'Drug producing reckless disregard for self-preservation.',
    Erg: 'A vast sea of sand dunes.',
    Facedancer: 'Tleilaxu shapeshifter able to mimic other people.',
    Faufreluches: 'The rigid Imperial class system; a place for everyone.',
    Fedaykin: "Fremen death-commandos devoted to Muad'Dib.",
    Filmbook: 'Shigawire spool teaching through subliminal imprinting.',
    Fremkit: 'A Fremen desert-survival kit.',
    Galach: 'The official language of the Imperium.',
    Gammu: 'Later name for the Harkonnen world Giedi Prime.',
    Ghola: 'A dead person regrown from cells in axlotl tanks.',
    Giedi: 'Harkonnen homeworld, Giedi Prime; industrial and grim.',
    Ginaz: 'World of the legendary Swordmaster school.',
    Glowglobe: 'A suspensor-borne floating light.',
    Grumman: "House Moritani's warlike homeworld.",
    Harkonnen: 'Cruel rival House, sworn enemies of the Atreides.',
    Harvester: 'Huge machine that mines spice from the sand.',
    Heighliner: 'Enormous Guild ship that folds space between worlds.',
    Holtzman: 'Physicist whose effect underlies shields and space-folding.',
    'Hunter-Seeker': 'Remote-controlled flying poisoned-needle assassin.',
    Imperium: 'The galaxy-wide feudal empire.',
    Ix: 'World of forbidden advanced-machine manufacturing.',
    Kaitain: 'Imperial capital planet of House Corrino.',
    Kanly: 'Formal, rule-bound vendetta between Houses.',
    Karama: 'A miracle; an act of the spirit world.',
    Kwisatz: 'The Bene Gesserit-bred messiah, the Kwisatz Haderach.',
    Landsraad: 'The assembly of the Great Houses.',
    Lasgun: 'Continuous-beam laser weapon; explodes against a shield.',
    Litany: 'The Bene Gesserit litany against fear.',
    Mahdi: 'Fremen messiah prophesied to lead them to paradise.',
    Maker: 'The Fremen name for a sandworm.',
    Maula: 'A spring-loaded dart pistol.',
    Missionaria: 'Bene Gesserit arm seeding protective superstitions on worlds.',
    Naib: 'A Fremen sietch leader, sworn to defend his people.',
    'No-ship': 'A ship invisible to prescience and detection.',
    Ornithopter: 'Flapping-wing aircraft, common Imperial transport.',
    Padishah: 'Title of the galactic Emperor.',
    Paracompass: 'Compass reading local magnetic anomalies, not the poles.',
    Prana: 'Muscle and body control in prana-bindu training.',
    Qanat: 'Open canal carrying water across the desert.',
    Qizarate: "Priesthood of Muad'Dib's later religion.",
    Rakis: 'A later name for the planet Arrakis.',
    Razzia: 'A raid, especially for slaves or guerrilla warfare.',
    Richese: 'World known for miniaturization and machine technology.',
    Salusa: 'Salusa Secundus, Corrino prison planet breeding Sardaukar.',
    Sandrider: 'A Fremen who mounts and rides a sandworm.',
    Sandtrout: 'Larval sandworm that encysts water underground.',
    Sandwalk: 'Rhythmless walking to avoid attracting sandworms.',
    Sapho: 'Juice heightening Mentat thought; stains the lips red.',
    Sardaukar: "The Emperor's fanatical elite soldiers.",
    Sayyadina: 'A Fremen priestess or reverend-mother acolyte.',
    Scattering: 'The great dispersal of humanity across the unknown universe.',
    Semuta: 'Narcotic drug paired with atonal music.',
    Shadout: 'Fremen title of honor meaning well-dipper.',
    'Shai-Hulud': "The great sandworm; the desert's old man.",
    Shaitan: 'Fremen name for Satan, and for the sandworm.',
    Shigawire: 'Metal-fiber vine used as a data-recording medium.',
    Snooper: 'Poison-sniffing device that checks food at table.',
    Spiceblow: 'Eruption where a sandworm expels a spice mass.',
    Stoneburner: 'Atomic weapon burning down through rock, blinding onlookers.',
    Suk: 'Imperial medical school with unbreakable conditioning.',
    Suspensor: 'Device nullifying gravity to float objects.',
    Swordmaster: 'Elite Ginaz-trained warrior and weapons instructor.',
    Tabr: "Sietch Tabr, Stilgar's Fremen stronghold.",
    Tanzerouft: 'The land of terror, deep southern desert.',
    Tau: 'The spice-orgy unity binding a Fremen community.',
    Thumper: 'Staked device beating the sand to summon a worm.',
    Tleilax: 'Secretive homeworld of the Bene Tleilax.',
    Tleilaxu: 'The Bene Tleilax; makers of gholas and Face Dancers.',
    Truthsayer: 'Bene Gesserit who detects lies, often via spice.',
    Tupile: 'Secret sanctuary planets for defeated Houses.',
    Verite: 'An Ecaz drug that compels the truth.',
    Wallach: 'Wallach IX, the Bene Gesserit Mother School.',
    Weirding: 'Fremen term for Bene Gesserit fighting ways.',
    Windtrap: 'Device condensing moisture from the air into water.',
  },
};
